#!/bin/bash

# Display information about the track playing
# Use i3-player-notify to receive updates on track change

set -euo pipefail
# set -x

path=/org/mpris/MediaPlayer2
interface=org.mpris.MediaPlayer2.Player

# unicode entities
u_play="&#xf04b;"
u_pause="&#xf04c;"
u_stop="&#xf04d;"
u_nbsp="&#x00a0;"
u_rocket="&#xf135;"
u_music="&#xf001;"
u_mic="&#xf130;"
u_disc="&#xf192;"

# Look for the services which are actually players, and stop if one is playing.
player=""
services=$(qdbus | (grep MediaPlayer2 || true))
for service in $services
do
    if [[ "$(qdbus $service $path $interface.CanControl || true)" == "true" ]]
    then
        player=$service
        break
    fi
done

if [[ ! "$player" ]]; then
    # if there is no player open, on right click,
    # spawn the program registered as default for audio/mpeg
    if [ "${BLOCK_BUTTON:-}" == '3' ]; then
        bin=$(binary-for-mime audio/mpeg)
        echo "Running $(basename "$bin")! $u_nbsp $u_rocket"
        "$bin" > /dev/null &
        exit 0
    else
        echo "<span color='#aaa'>(no player running)</span> $u_nbsp $u_stop"
        exit 0
    fi
fi

case ${BLOCK_BUTTON:-} in
  1) qdbus $player $path $interface.PlayPause ;;
  3) qdbus $player $path org.mpris.MediaPlayer2.Raise ;;
  4) qdbus $player $path $interface.Previous ;;
  5) qdbus $player $path $interface.Next ;;
esac

play_status=$(qdbus $player $path $interface.PlaybackStatus)
case "$play_status" in
    Playing)
        icon="$u_play" ;;
    Paused)
        icon="$u_pause" ;;
    Stopped)
        icon="$u_stop" ;;
    *)
        icon="$play_status" ;;
esac

if [[ "$play_status" == "Stopped" ]]; then
    echo "<span color='#aaa'>(nothing playing)</span> $u_nbsp $icon"
    exit 0
fi

function escape_html () {
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
}

title=$(qdbus $player $path $interface.Metadata \
    | (grep xesam:title: || true) | cut -d " " -f 2- | escape_html)
rv="$u_music ${title:-unknown}"

album=$(qdbus $player $path $interface.Metadata \
    | (grep xesam:album: || true) | cut -d " " -f 2- | escape_html)
[ "$album" ] && rv="$u_disc $album $u_nbsp $rv"

artist=$(qdbus $player $path $interface.Metadata \
    | (grep xesam:artist: || true) | cut -d " " -f 2- | escape_html)
[ "$artist" ] && rv="$u_mic $artist $u_nbsp $rv"

track=$(qdbus $player $path $interface.Metadata \
    | (grep xesam:trackNumber: || true) | cut -d " " -f 2-)
[ "$track" ] && rv="$rv $u_nbsp #$track"

echo "$rv $u_nbsp $icon"
